### PR TITLE
Improve error handling in firewall rules

### PR DESCRIPTION
**Pull request by Markliniubility**

### CODE REVIEW

**Comment by xiaoyang-sde** [comment]
```ts
try {
  await useFirewall(context, () => null);
} catch (error) {
  expect(error.message).toMatch('You don\'t have permission to access this service.');
}
```

**Comment by Markliniubility** [comment]
> https://jestjs.io/docs/tutorial-async#error-handling

I found the docs that you mentioned, but I wonder why the method mentioned in https://jestjs.io/docs/expect#tothrowerror doesn't work, since both of them are in the same verison

**Review by lorenzoc25 — APPROVED** [review]

**Comment by xiaoyang-sde** [comment]
> > https://jestjs.io/docs/tutorial-async#error-handling
> 
> I found the docs that you mentioned, but I wonder why the method mentioned in https://jestjs.io/docs/expect#tothrowerror doesn't work, since both of them are in the same verison

`expect().resolves.toThrow(error)`

**Review by xiaoyang-sde — APPROVED** [review]
Thanks for your contribution!

**Pull request merged**
